// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Veracode.ApiClients.Applications.Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// AppCustomFieldValue
    /// </summary>
    public partial class AppCustomFieldValue
    {
        /// <summary>
        /// Initializes a new instance of the AppCustomFieldValue class.
        /// </summary>
        public AppCustomFieldValue()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AppCustomFieldValue class.
        /// </summary>
        /// <param name="created">The date and time when the application was
        /// created. The date/time format is per RFC3339 and ISO-8601, and the
        /// timezone is UTC. Example: 2019-04-12T23:20:50.52Z.</param>
        /// <param name="id">Unique identifier of the category.</param>
        public AppCustomFieldValue(AppCustomFieldName appCustomFieldName = default(AppCustomFieldName), System.DateTime? created = default(System.DateTime?), int? fieldNameId = default(int?), int? id = default(int?), string value = default(string))
        {
            AppCustomFieldName = appCustomFieldName;
            Created = created;
            FieldNameId = fieldNameId;
            Id = id;
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "app_custom_field_name")]
        public AppCustomFieldName AppCustomFieldName { get; set; }

        /// <summary>
        /// Gets the date and time when the application was created. The
        /// date/time format is per RFC3339 and ISO-8601, and the timezone is
        /// UTC. Example: 2019-04-12T23:20:50.52Z.
        /// </summary>
        [JsonProperty(PropertyName = "created")]
        public System.DateTime? Created { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "field_name_id")]
        public int? FieldNameId { get; set; }

        /// <summary>
        /// Gets or sets unique identifier of the category.
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

    }
}
