// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Veracode.ApiClients.Applications.Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// AppCustomFieldName
    /// </summary>
    public partial class AppCustomFieldName
    {
        /// <summary>
        /// Initializes a new instance of the AppCustomFieldName class.
        /// </summary>
        public AppCustomFieldName()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AppCustomFieldName class.
        /// </summary>
        /// <param name="created">The date and time when the application was
        /// created. The date/time format is per RFC3339 and ISO-8601, and the
        /// timezone is UTC. Example: 2019-04-12T23:20:50.52Z.</param>
        /// <param name="id">Unique identifier of the category.</param>
        /// <param name="modified">The date and time when the application was
        /// modified. The date/time format is per RFC3339 and ISO-8601, and the
        /// timezone is UTC. Example: 2019-04-12T23:20:50.52Z.</param>
        public AppCustomFieldName(System.DateTime? created = default(System.DateTime?), int? id = default(int?), System.DateTime? modified = default(System.DateTime?), string name = default(string), int? organizationId = default(int?), int? sortOrder = default(int?))
        {
            Created = created;
            Id = id;
            Modified = modified;
            Name = name;
            OrganizationId = organizationId;
            SortOrder = sortOrder;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets the date and time when the application was created. The
        /// date/time format is per RFC3339 and ISO-8601, and the timezone is
        /// UTC. Example: 2019-04-12T23:20:50.52Z.
        /// </summary>
        [JsonProperty(PropertyName = "created")]
        public System.DateTime? Created { get; private set; }

        /// <summary>
        /// Gets unique identifier of the category.
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; private set; }

        /// <summary>
        /// Gets the date and time when the application was modified. The
        /// date/time format is per RFC3339 and ISO-8601, and the timezone is
        /// UTC. Example: 2019-04-12T23:20:50.52Z.
        /// </summary>
        [JsonProperty(PropertyName = "modified")]
        public System.DateTime? Modified { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "organization_id")]
        public int? OrganizationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sort_order")]
        public int? SortOrder { get; set; }

    }
}
