// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Veracode.ApiClients.ApplicationsApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// ApplicationScan
    /// </summary>
    /// <remarks>
    /// Reference to the latest scan of this application.
    /// </remarks>
    public partial class ApplicationScan
    {
        /// <summary>
        /// Initializes a new instance of the ApplicationScan class.
        /// </summary>
        public ApplicationScan()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ApplicationScan class.
        /// </summary>
        /// <param name="modifiedDate">The date when the scan results were
        /// published. The date/time format is per RFC3339 and ISO-8601, and
        /// the timezone is UTC. Example: 2019-04-12T23:20:50.52Z.</param>
        /// <param name="scanType">Type of scan in which this finding was
        /// discovered. Possible values include: 'STATIC', 'DYNAMIC', 'MANUAL',
        /// 'SCA'</param>
        /// <param name="scanUrl">Unique path to the latest scan.</param>
        /// <param name="status">Scan status. Possible values include:
        /// 'CREATED', 'UNPUBLISHED', 'DELETED', 'PARTIAL_PUBLISH',
        /// 'PARTIAL_UNPUBLISH', 'INCOMPLETE', 'SCAN_SUBMITTED', 'IN_QUEUE',
        /// 'STOPPING', 'PAUSING', 'IN_PROGRESS', 'ANALYSIS_ERRORS',
        /// 'SCAN_CANCELED', 'INTERNAL_REVIEW', 'VERIFYING_RESULTS',
        /// 'SUBMITTED_FOR_NTO_PRE_SCAN', 'SUBMITTED_FOR_DYNAMIC_PRE_SCAN',
        /// 'PRE_SCAN_FAILED', 'READY_TO_SUBMIT', 'NTO_PENDING_SUBMISSION',
        /// 'PRE_SCAN_COMPLETE', 'MODULE_SELECTION_REQUIRED',
        /// 'PENDING_VENDOR_ACCEPTANCE', 'SHOW_OSRDB', 'PUBLISHED',
        /// 'PUBLISHED_TO_VENDOR', 'PUBLISHED_TO_ENTERPRISE',
        /// 'PENDING_ACCOUNT_APPROVAL', 'PENDING_LEGAL_AGREEMENT',
        /// 'SCAN_IN_PROGRESS', 'SCAN_IN_PROGRESS_PARTIAL_RESULTS_READY',
        /// 'PROMOTE_IN_PROGRESS', 'PRE_SCAN_CANCELED',
        /// 'NTO_PRE_SCAN_CANCELED', 'SCAN_HELD_APPROVAL',
        /// 'SCAN_HELD_LOGIN_INSTRUCTIONS', 'SCAN_HELD_LOGIN',
        /// 'SCAN_HELD_INSTRUCTIONS', 'SCAN_HELD_HOLDS_FINISHED',
        /// 'SCAN_REQUESTED', 'TIMEFRAMEPENDING_ID', 'PAUSED_ID',
        /// 'STATIC_VALIDATING_UPLOAD', 'PUBLISHED_TO_ENTERPRISEINT'</param>
        public ApplicationScan(string internalStatus = default(string), System.DateTime? modifiedDate = default(System.DateTime?), string scanType = default(string), string scanUrl = default(string), string status = default(string))
        {
            InternalStatus = internalStatus;
            ModifiedDate = modifiedDate;
            ScanType = scanType;
            ScanUrl = scanUrl;
            Status = status;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "internal_status")]
        public string InternalStatus { get; set; }

        /// <summary>
        /// Gets the date when the scan results were published. The date/time
        /// format is per RFC3339 and ISO-8601, and the timezone is UTC.
        /// Example: 2019-04-12T23:20:50.52Z.
        /// </summary>
        [JsonProperty(PropertyName = "modified_date")]
        public System.DateTime? ModifiedDate { get; private set; }

        /// <summary>
        /// Gets type of scan in which this finding was discovered. Possible
        /// values include: 'STATIC', 'DYNAMIC', 'MANUAL', 'SCA'
        /// </summary>
        [JsonProperty(PropertyName = "scan_type")]
        public string ScanType { get; private set; }

        /// <summary>
        /// Gets unique path to the latest scan.
        /// </summary>
        [JsonProperty(PropertyName = "scan_url")]
        public string ScanUrl { get; private set; }

        /// <summary>
        /// Gets or sets scan status. Possible values include: 'CREATED',
        /// 'UNPUBLISHED', 'DELETED', 'PARTIAL_PUBLISH', 'PARTIAL_UNPUBLISH',
        /// 'INCOMPLETE', 'SCAN_SUBMITTED', 'IN_QUEUE', 'STOPPING', 'PAUSING',
        /// 'IN_PROGRESS', 'ANALYSIS_ERRORS', 'SCAN_CANCELED',
        /// 'INTERNAL_REVIEW', 'VERIFYING_RESULTS',
        /// 'SUBMITTED_FOR_NTO_PRE_SCAN', 'SUBMITTED_FOR_DYNAMIC_PRE_SCAN',
        /// 'PRE_SCAN_FAILED', 'READY_TO_SUBMIT', 'NTO_PENDING_SUBMISSION',
        /// 'PRE_SCAN_COMPLETE', 'MODULE_SELECTION_REQUIRED',
        /// 'PENDING_VENDOR_ACCEPTANCE', 'SHOW_OSRDB', 'PUBLISHED',
        /// 'PUBLISHED_TO_VENDOR', 'PUBLISHED_TO_ENTERPRISE',
        /// 'PENDING_ACCOUNT_APPROVAL', 'PENDING_LEGAL_AGREEMENT',
        /// 'SCAN_IN_PROGRESS', 'SCAN_IN_PROGRESS_PARTIAL_RESULTS_READY',
        /// 'PROMOTE_IN_PROGRESS', 'PRE_SCAN_CANCELED',
        /// 'NTO_PRE_SCAN_CANCELED', 'SCAN_HELD_APPROVAL',
        /// 'SCAN_HELD_LOGIN_INSTRUCTIONS', 'SCAN_HELD_LOGIN',
        /// 'SCAN_HELD_INSTRUCTIONS', 'SCAN_HELD_HOLDS_FINISHED',
        /// 'SCAN_REQUESTED', 'TIMEFRAMEPENDING_ID', 'PAUSED_ID',
        /// 'STATIC_VALIDATING_UPLOAD', 'PUBLISHED_TO_ENTERPRISEINT'
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

    }
}
