// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Veracode.ApiClients.ApplicationsApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// ApplicationProfile
    /// </summary>
    public partial class ApplicationProfile
    {
        /// <summary>
        /// Initializes a new instance of the ApplicationProfile class.
        /// </summary>
        public ApplicationProfile()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ApplicationProfile class.
        /// </summary>
        /// <param name="businessCriticality">Possible values include:
        /// 'VERY_HIGH', 'HIGH', 'MEDIUM', 'LOW', 'VERY_LOW'</param>
        public ApplicationProfile(string archerAppName = default(string), string businessCriticality = default(string), IList<BusinessOwner> businessOwners = default(IList<BusinessOwner>), BusinessUnit businessUnit = default(BusinessUnit), IList<AppCustomFieldValue> customFieldValues = default(IList<AppCustomFieldValue>), IList<CustomNameValue> customFields = default(IList<CustomNameValue>), string description = default(string), string name = default(string), IList<AppPolicy> policies = default(IList<AppPolicy>), ApplicationSettings settings = default(ApplicationSettings), string tags = default(string), IList<AppTeam> teams = default(IList<AppTeam>))
        {
            ArcherAppName = archerAppName;
            BusinessCriticality = businessCriticality;
            BusinessOwners = businessOwners;
            BusinessUnit = businessUnit;
            CustomFieldValues = customFieldValues;
            CustomFields = customFields;
            Description = description;
            Name = name;
            Policies = policies;
            Settings = settings;
            Tags = tags;
            Teams = teams;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "archer_app_name")]
        public string ArcherAppName { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'VERY_HIGH', 'HIGH',
        /// 'MEDIUM', 'LOW', 'VERY_LOW'
        /// </summary>
        [JsonProperty(PropertyName = "business_criticality")]
        public string BusinessCriticality { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "business_owners")]
        public IList<BusinessOwner> BusinessOwners { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "business_unit")]
        public BusinessUnit BusinessUnit { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "custom_field_values")]
        public IList<AppCustomFieldValue> CustomFieldValues { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "custom_fields")]
        public IList<CustomNameValue> CustomFields { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "policies")]
        public IList<AppPolicy> Policies { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "settings")]
        public ApplicationSettings Settings { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tags")]
        public string Tags { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "teams")]
        public IList<AppTeam> Teams { get; set; }

    }
}
