// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Veracode.ApiClients.ApplicationsApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// AppTeam
    /// </summary>
    public partial class AppTeam
    {
        /// <summary>
        /// Initializes a new instance of the AppTeam class.
        /// </summary>
        public AppTeam()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AppTeam class.
        /// </summary>
        /// <param name="guid">The team ID in the Veracode Identity
        /// API.</param>
        /// <param name="teamId">The legacy team_id.</param>
        /// <param name="teamName">Team name.</param>
        public AppTeam(string guid = default(string), int? teamId = default(int?), string teamName = default(string))
        {
            Guid = guid;
            TeamId = teamId;
            TeamName = teamName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the team ID in the Veracode Identity API.
        /// </summary>
        [JsonProperty(PropertyName = "guid")]
        public string Guid { get; set; }

        /// <summary>
        /// Gets the legacy team_id.
        /// </summary>
        [JsonProperty(PropertyName = "team_id")]
        public int? TeamId { get; private set; }

        /// <summary>
        /// Gets team name.
        /// </summary>
        [JsonProperty(PropertyName = "team_name")]
        public string TeamName { get; private set; }

    }
}
