// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Veracode.ApiClients.DynamicFlawApi
{
    using Microsoft.Rest;
    using Models;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Replacement for
    /// https://analysiscenter.veracode.com/api/5.0/getdynamicflaws.do
    /// </summary>
    public partial interface IDynamicFlawApiClient : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }


        /// <summary>
        /// Returns information on a specific dynamic flaw.
        /// </summary>
        /// <remarks>
        /// Returns detailed information about a single dynamic flaw, including
        /// the CWE, description, recommendation, and associated HTTP requests.
        /// </remarks>
        /// <param name='appGuid'>
        /// GUID for the application.
        /// </param>
        /// <param name='issueId'>
        /// Unique issue ID for the scanned application.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> GetDynamicFlawInfoWithHttpMessagesAsync(string appGuid, string issueId, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

    }
}
