// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Veracode.ApiClients.SummaryReportApi
{
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for SummaryReportApi.
    /// </summary>
    public static partial class SummaryReportApiExtensions
    {
            /// <summary>
            /// Returns a Summary Report of a scan.
            /// </summary>
            /// <remarks>
            /// Returns a Summary Report of a static analysis, dynamic analysis or manual
            /// penetration test.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='appGuid'>
            /// GUID of the application.
            /// </param>
            /// <param name='buildId'>
            /// ID of the build in which the scan ran. Default is the latest build_id.
            /// </param>
            /// <param name='context'>
            /// GUID of the associated development sandbox, if specified. The Summary
            /// Report is relative to this context parameter.
            /// </param>
            public static SummaryReport GetSummaryReport(this ISummaryReportApi operations, string appGuid, IList<string> buildId = default(IList<string>), IList<string> context = default(IList<string>))
            {
                return operations.GetSummaryReportAsync(appGuid, buildId, context).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Returns a Summary Report of a scan.
            /// </summary>
            /// <remarks>
            /// Returns a Summary Report of a static analysis, dynamic analysis or manual
            /// penetration test.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='appGuid'>
            /// GUID of the application.
            /// </param>
            /// <param name='buildId'>
            /// ID of the build in which the scan ran. Default is the latest build_id.
            /// </param>
            /// <param name='context'>
            /// GUID of the associated development sandbox, if specified. The Summary
            /// Report is relative to this context parameter.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<SummaryReport> GetSummaryReportAsync(this ISummaryReportApi operations, string appGuid, IList<string> buildId = default(IList<string>), IList<string> context = default(IList<string>), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetSummaryReportWithHttpMessagesAsync(appGuid, buildId, context, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
