// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Veracode.ApiClients.SCAAgentApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// AgentToken
    /// </summary>
    public partial class AgentToken : AgentTokenWithoutAccessToken
    {
        /// <summary>
        /// Initializes a new instance of the AgentToken class.
        /// </summary>
        public AgentToken()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AgentToken class.
        /// </summary>
        /// <param name="accessToken">Access token for the agent. This field is
        /// only visible when a token is first created and returned.</param>
        public AgentToken(IList<Link> _links = default(IList<Link>), string createdBy = default(string), System.DateTime? createdDate = default(System.DateTime?), string id = default(string), string accessToken = default(string))
            : base(_links, createdBy, createdDate, id)
        {
            AccessToken = accessToken;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets access token for the agent. This field is only visible
        /// when a token is first created and returned.
        /// </summary>
        [JsonProperty(PropertyName = "access_token")]
        public string AccessToken { get; set; }

    }
}
