// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Veracode.ApiClients.SCAAgent.Api.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// ComponentMetrics
    /// </summary>
    public partial class ComponentMetrics
    {
        /// <summary>
        /// Initializes a new instance of the ComponentMetrics class.
        /// </summary>
        public ComponentMetrics()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ComponentMetrics class.
        /// </summary>
        public ComponentMetrics(long? libraryId = default(long?), long? age = default(long?), string codeRepoUrl = default(string), double? commitActivity = default(double?), double? commitVolume = default(double?), long? filesChanged = default(long?), long? linesAdded = default(long?), long? linesRemoved = default(long?), long? numCommitsPast12Months = default(long?), long? numCommitsPast30Days = default(long?), long? numCommitters = default(long?), long? numberOfCommits = default(long?), long? stagnation = default(long?), object library = default(object), IList<string> nonVulnVersions = default(IList<string>))
        {
            LibraryId = libraryId;
            Age = age;
            CodeRepoUrl = codeRepoUrl;
            CommitActivity = commitActivity;
            CommitVolume = commitVolume;
            FilesChanged = filesChanged;
            LinesAdded = linesAdded;
            LinesRemoved = linesRemoved;
            NumCommitsPast12Months = numCommitsPast12Months;
            NumCommitsPast30Days = numCommitsPast30Days;
            NumCommitters = numCommitters;
            NumberOfCommits = numberOfCommits;
            Stagnation = stagnation;
            Library = library;
            NonVulnVersions = nonVulnVersions;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "library_id")]
        public long? LibraryId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "age")]
        public long? Age { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "code_repo_url")]
        public string CodeRepoUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "commit_activity")]
        public double? CommitActivity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "commit_volume")]
        public double? CommitVolume { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "files_changed")]
        public long? FilesChanged { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lines_added")]
        public long? LinesAdded { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lines_removed")]
        public long? LinesRemoved { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "num_commits_past12_months")]
        public long? NumCommitsPast12Months { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "num_commits_past30_days")]
        public long? NumCommitsPast30Days { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "num_committers")]
        public long? NumCommitters { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "number_of_commits")]
        public long? NumberOfCommits { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "stagnation")]
        public long? Stagnation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "library")]
        public object Library { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "non_vuln_versions")]
        public IList<string> NonVulnVersions { get; set; }

    }
}
