// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Veracode.ApiClients.SCAAgentApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// CreateWorkspaceModel
    /// </summary>
    public partial class CreateWorkspaceModel
    {
        /// <summary>
        /// Initializes a new instance of the CreateWorkspaceModel class.
        /// </summary>
        public CreateWorkspaceModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateWorkspaceModel class.
        /// </summary>
        /// <param name="name">The workspace name. Must be between 3 and 20
        /// letters, numbers, spaces, hyphens, single-quotes or underscores
        /// (must start with a letter).</param>
        public CreateWorkspaceModel(string name = default(string))
        {
            Name = name;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the workspace name. Must be between 3 and 20 letters,
        /// numbers, spaces, hyphens, single-quotes or underscores (must start
        /// with a letter).
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

    }
}
