// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Veracode.ApiClients.SCAAgent.Api.Models
{
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// LibrarySummary
    /// </summary>
    public partial class LibrarySummary
    {
        /// <summary>
        /// Initializes a new instance of the LibrarySummary class.
        /// </summary>
        public LibrarySummary()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the LibrarySummary class.
        /// </summary>
        public LibrarySummary(IList<Link> _links = default(IList<Link>), bool? direct = default(bool?), string id = default(string), string latestVersion = default(string), System.DateTime? latestVersionReleaseDate = default(System.DateTime?), string name = default(string), System.DateTime? releaseDate = default(System.DateTime?), bool? transitive = default(bool?), string version = default(string))
        {
            this._links = _links;
            Direct = direct;
            Id = id;
            LatestVersion = latestVersion;
            LatestVersionReleaseDate = latestVersionReleaseDate;
            Name = name;
            ReleaseDate = releaseDate;
            Transitive = transitive;
            Version = version;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "_links")]
        public IList<Link> _links { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "direct")]
        public bool? Direct { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "latest_version")]
        public string LatestVersion { get; set; }

        /// <summary>
        /// </summary>
        [JsonConverter(typeof(DateJsonConverter))]
        [JsonProperty(PropertyName = "latest_version_release_date")]
        public System.DateTime? LatestVersionReleaseDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonConverter(typeof(DateJsonConverter))]
        [JsonProperty(PropertyName = "release_date")]
        public System.DateTime? ReleaseDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transitive")]
        public bool? Transitive { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "version")]
        public string Version { get; set; }

    }
}
