// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Veracode.ApiClients.SCAAgentApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// LibraryDetailed
    /// </summary>
    public partial class LibraryDetailed
    {
        /// <summary>
        /// Initializes a new instance of the LibraryDetailed class.
        /// </summary>
        public LibraryDetailed()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the LibraryDetailed class.
        /// </summary>
        /// <param name="language">Possible values include: 'java', 'js',
        /// 'ruby', 'python', 'go', 'php', 'objectivec', 'cpp',
        /// 'csharp'</param>
        public LibraryDetailed(IList<Link> _links = default(IList<Link>), bool? direct = default(bool?), string id = default(string), string language = default(string), string latestVersion = default(string), System.DateTime? latestVersionReleaseDate = default(System.DateTime?), IList<LicenseSummary> licenses = default(IList<LicenseSummary>), long? lineCount = default(long?), string name = default(string), System.DateTime? releaseDate = default(System.DateTime?), bool? transitive = default(bool?), string version = default(string))
        {
            this._links = _links;
            Direct = direct;
            Id = id;
            Language = language;
            LatestVersion = latestVersion;
            LatestVersionReleaseDate = latestVersionReleaseDate;
            Licenses = licenses;
            LineCount = lineCount;
            Name = name;
            ReleaseDate = releaseDate;
            Transitive = transitive;
            Version = version;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "_links")]
        public IList<Link> _links { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "direct")]
        public bool? Direct { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'java', 'js', 'ruby',
        /// 'python', 'go', 'php', 'objectivec', 'cpp', 'csharp'
        /// </summary>
        [JsonProperty(PropertyName = "language")]
        public string Language { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "latest_version")]
        public string LatestVersion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "latest_version_release_date")]
        public System.DateTime? LatestVersionReleaseDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "licenses")]
        public IList<LicenseSummary> Licenses { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "line_count")]
        public long? LineCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "release_date")]
        public System.DateTime? ReleaseDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transitive")]
        public bool? Transitive { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "version")]
        public string Version { get; set; }

    }
}
