// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Veracode.ApiClients.SCAAgent.Api.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// BOM Metadata Object
    /// </summary>
    public partial class Metadata
    {
        /// <summary>
        /// Initializes a new instance of the Metadata class.
        /// </summary>
        public Metadata()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Metadata class.
        /// </summary>
        /// <param name="timestamp">Timestamp</param>
        /// <param name="tools">Creation Tools</param>
        /// <param name="component">Component</param>
        /// <param name="author">Supplier</param>
        /// <param name="supplier">Supplier</param>
        public Metadata(System.DateTime? timestamp = default(System.DateTime?), IList<Tool> tools = default(IList<Tool>), Component component = default(Component), OrganizationalContact author = default(OrganizationalContact), OrganizationalEntity supplier = default(OrganizationalEntity))
        {
            Timestamp = timestamp;
            Tools = tools;
            Component = component;
            Author = author;
            Supplier = supplier;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets timestamp
        /// </summary>
        /// <remarks>
        /// The date and time (timestamp) when the BOM was created.
        /// </remarks>
        [JsonProperty(PropertyName = "timestamp")]
        public System.DateTime? Timestamp { get; set; }

        /// <summary>
        /// Gets or sets creation Tools
        /// </summary>
        /// <remarks>
        /// The tools used in the creation of the BOM.
        /// </remarks>
        [JsonProperty(PropertyName = "tools")]
        public IList<Tool> Tools { get; set; }

        /// <summary>
        /// Gets or sets component
        /// </summary>
        /// <remarks>
        /// The component that the BOM describes.
        /// </remarks>
        [JsonProperty(PropertyName = "component")]
        public Component Component { get; set; }

        /// <summary>
        /// Gets or sets supplier
        /// </summary>
        /// <remarks>
        /// The organization that supplied the component that the BOM
        /// describes. The supplier may often be the manufacturer, but may also
        /// be a distributor or repackager.
        /// </remarks>
        [JsonProperty(PropertyName = "author")]
        public OrganizationalContact Author { get; set; }

        /// <summary>
        /// Gets or sets supplier
        /// </summary>
        /// <remarks>
        /// The organization that supplied the component that the BOM
        /// describes. The supplier may often be the manufacturer, but may also
        /// be a distributor or repackager.
        /// </remarks>
        [JsonProperty(PropertyName = "supplier")]
        public OrganizationalEntity Supplier { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Component != null)
            {
                Component.Validate();
            }
        }
    }
}
