// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Veracode.ApiClients.SCAAgent.Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ProjectLinkedApplication
    {
        /// <summary>
        /// Initializes a new instance of the ProjectLinkedApplication class.
        /// </summary>
        public ProjectLinkedApplication()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProjectLinkedApplication class.
        /// </summary>
        public ProjectLinkedApplication(string guid = default(string), string name = default(string))
        {
            Guid = guid;
            Name = name;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "guid")]
        public string Guid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

    }
}
