// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Veracode.ApiClients.SCAAgentApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Project
    /// </summary>
    public partial class Project
    {
        /// <summary>
        /// Initializes a new instance of the Project class.
        /// </summary>
        public Project()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Project class.
        /// </summary>
        public Project(IList<Link> _links = default(IList<Link>), IList<string> branches = default(IList<string>), string id = default(string), IList<string> languages = default(IList<string>), System.DateTime? lastScanDate = default(System.DateTime?), int? libraryIssuesCount = default(int?), int? licenseIssuesCount = default(int?), string name = default(string), string siteId = default(string), int? totalIssuesCount = default(int?), int? vulnerabilityIssuesCount = default(int?), ProjectLinkedApplication linkedApplication = default(ProjectLinkedApplication))
        {
            this._links = _links;
            Branches = branches;
            Id = id;
            Languages = languages;
            LastScanDate = lastScanDate;
            LibraryIssuesCount = libraryIssuesCount;
            LicenseIssuesCount = licenseIssuesCount;
            Name = name;
            SiteId = siteId;
            TotalIssuesCount = totalIssuesCount;
            VulnerabilityIssuesCount = vulnerabilityIssuesCount;
            LinkedApplication = linkedApplication;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "_links")]
        public IList<Link> _links { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "branches")]
        public IList<string> Branches { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "languages")]
        public IList<string> Languages { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "last_scan_date")]
        public System.DateTime? LastScanDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "library_issues_count")]
        public int? LibraryIssuesCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "license_issues_count")]
        public int? LicenseIssuesCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "site_id")]
        public string SiteId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "total_issues_count")]
        public int? TotalIssuesCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "vulnerability_issues_count")]
        public int? VulnerabilityIssuesCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "linked_application")]
        public ProjectLinkedApplication LinkedApplication { get; set; }

    }
}
