// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Veracode.ApiClients.SCAAgent.Api.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Resources[AgentToken]
    /// </summary>
    public partial class ResourcesAgentToken
    {
        /// <summary>
        /// Initializes a new instance of the ResourcesAgentToken class.
        /// </summary>
        public ResourcesAgentToken()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ResourcesAgentToken class.
        /// </summary>
        public ResourcesAgentToken(IList<AgentToken> _embedded = default(IList<AgentToken>), IList<Link> _links = default(IList<Link>))
        {
            this._embedded = _embedded;
            this._links = _links;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "_embedded")]
        public IList<AgentToken> _embedded { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "_links")]
        public IList<Link> _links { get; set; }

    }
}
