// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Veracode.ApiClients.SCAAgentApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Resources«AgentSummary»
    /// </summary>
    public partial class ResourcesAgentSummary
    {
        /// <summary>
        /// Initializes a new instance of the ResourcesAgentSummary class.
        /// </summary>
        public ResourcesAgentSummary()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ResourcesAgentSummary class.
        /// </summary>
        public ResourcesAgentSummary(IList<AgentSummary> _embedded = default(IList<AgentSummary>), IList<Link> _links = default(IList<Link>))
        {
            this._embedded = _embedded;
            this._links = _links;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "_embedded")]
        public IList<AgentSummary> _embedded { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "_links")]
        public IList<Link> _links { get; set; }

    }
}
