// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Veracode.ApiClients.SCAAgent.Api.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class SbomspdxCreationInfo
    {
        /// <summary>
        /// Initializes a new instance of the SbomspdxCreationInfo class.
        /// </summary>
        public SbomspdxCreationInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SbomspdxCreationInfo class.
        /// </summary>
        /// <param name="comment">SPDX specification version. Current version
        /// is SPDX-2.3</param>
        /// <param name="created">When the SPDX document was originally
        /// created. The date is to be specified according to combined date and
        /// time in UTC format as specified in ISO 8601 standard.</param>
        /// <param name="creators">An optional field for creators of the SPDX
        /// document to provide general comments about the creation of the SPDX
        /// document or any other relevant comment not included in the other
        /// fields.</param>
        public SbomspdxCreationInfo(string comment = default(string), System.DateTime? created = default(System.DateTime?), IList<string> creators = default(IList<string>))
        {
            Comment = comment;
            Created = created;
            Creators = creators;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets SPDX specification version. Current version is
        /// SPDX-2.3
        /// </summary>
        [JsonProperty(PropertyName = "comment")]
        public string Comment { get; set; }

        /// <summary>
        /// Gets or sets when the SPDX document was originally created. The
        /// date is to be specified according to combined date and time in UTC
        /// format as specified in ISO 8601 standard.
        /// </summary>
        [JsonProperty(PropertyName = "created")]
        public System.DateTime? Created { get; set; }

        /// <summary>
        /// Gets or sets an optional field for creators of the SPDX document to
        /// provide general comments about the creation of the SPDX document or
        /// any other relevant comment not included in the other fields.
        /// </summary>
        [JsonProperty(PropertyName = "creators")]
        public IList<string> Creators { get; set; }

    }
}
