// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Veracode.ApiClients.SCAAgentApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Tool
    /// </summary>
    /// <remarks>
    /// Information about the automated or manual tool used.
    /// </remarks>
    public partial class Tool
    {
        /// <summary>
        /// Initializes a new instance of the Tool class.
        /// </summary>
        public Tool()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Tool class.
        /// </summary>
        /// <param name="vendor">The name of the vendor who created the
        /// tool.</param>
        /// <param name="name">The name of the tool.</param>
        /// <param name="version">The version of the tool.</param>
        public Tool(string vendor = default(string), string name = default(string), string version = default(string))
        {
            Vendor = vendor;
            Name = name;
            Version = version;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the name of the vendor who created the tool.
        /// </summary>
        [JsonProperty(PropertyName = "vendor")]
        public string Vendor { get; set; }

        /// <summary>
        /// Gets or sets the name of the tool.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the version of the tool.
        /// </summary>
        [JsonProperty(PropertyName = "version")]
        public string Version { get; set; }

    }
}
