// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Veracode.ApiClients.IdentityApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ResourceOfFeature
    {
        /// <summary>
        /// Initializes a new instance of the ResourceOfFeature class.
        /// </summary>
        public ResourceOfFeature()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ResourceOfFeature class.
        /// </summary>
        /// <param name="active">Flag indicating if this feature is currently
        /// active.</param>
        /// <param name="featureDescription">The short description for this
        /// feature.</param>
        /// <param name="featureId">The feature ID in the Veracode Identity
        /// API.</param>
        /// <param name="featureLegacyId">The feature ID in the Veracode
        /// database.</param>
        /// <param name="featureName">The feature name.</param>
        /// <param name="overrideable">Flag indicating if this feature is
        /// overrideable.</param>
        public ResourceOfFeature(bool? active = default(bool?), string featureDescription = default(string), string featureId = default(string), int? featureLegacyId = default(int?), string featureName = default(string), object _links = default(object), bool? overrideable = default(bool?))
        {
            Active = active;
            FeatureDescription = featureDescription;
            FeatureId = featureId;
            FeatureLegacyId = featureLegacyId;
            FeatureName = featureName;
            this._links = _links;
            Overrideable = overrideable;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets flag indicating if this feature is currently active.
        /// </summary>
        [JsonProperty(PropertyName = "active")]
        public bool? Active { get; set; }

        /// <summary>
        /// Gets or sets the short description for this feature.
        /// </summary>
        [JsonProperty(PropertyName = "feature_description")]
        public string FeatureDescription { get; set; }

        /// <summary>
        /// Gets or sets the feature ID in the Veracode Identity API.
        /// </summary>
        [JsonProperty(PropertyName = "feature_id")]
        public string FeatureId { get; set; }

        /// <summary>
        /// Gets or sets the feature ID in the Veracode database.
        /// </summary>
        [JsonProperty(PropertyName = "feature_legacy_id")]
        public int? FeatureLegacyId { get; set; }

        /// <summary>
        /// Gets or sets the feature name.
        /// </summary>
        [JsonProperty(PropertyName = "feature_name")]
        public string FeatureName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "_links")]
        public object _links { get; set; }

        /// <summary>
        /// Gets or sets flag indicating if this feature is overrideable.
        /// </summary>
        [JsonProperty(PropertyName = "overrideable")]
        public bool? Overrideable { get; set; }

    }
}
