// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Veracode.ApiClients.IdentityApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// A single SKU.
    /// </summary>
    public partial class Sku
    {
        /// <summary>
        /// Initializes a new instance of the Sku class.
        /// </summary>
        public Sku()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Sku class.
        /// </summary>
        /// <param name="defaultUnitsPurchased">The number of deafult units of
        /// this SKU that can be purchased.</param>
        /// <param name="deleted">Flag indicating if this SKU was soft
        /// deleted.</param>
        /// <param name="discontinued">Flag indicating if this SKU is
        /// discontinued.</param>
        /// <param name="publishType">Enum indicating the publish type of this
        /// SKU. Possible values include: 'PLATFORM', 'GREENLIGHT'</param>
        /// <param name="skuAnalysisType">Enum indicating the SKU analysis type
        /// of this SKU. Possible values include: 'STATIC', 'DYNAMIC',
        /// 'STATIC_AND_DYNAMIC', 'NOT_APPLICABLE', 'DYNAMIC_ANALYSIS'</param>
        /// <param name="skuDescription">The short description for this
        /// SKU.</param>
        /// <param name="skuId">The SKU ID in the Veracode Identity
        /// API.</param>
        /// <param name="skuLegacyId">The SKU ID in the Veracode
        /// database.</param>
        /// <param name="skuName">The SKU name.</param>
        /// <param name="skuType">Enum indicating the SKU type of this SKU.
        /// Possible values include: 'SDLC', 'COTS_ENTERPRISE', 'ELEARNING',
        /// 'APPLICATION', 'CSM', 'DISCOVERY', 'DYNAMICMP', 'SCA', 'DYN_APP',
        /// 'DYN_SCANS', 'DYN_SCANNER', 'SC_ACCEL_NEXTDAY', 'SC_SCA',
        /// 'SCA_AND_SC', 'SCA_UNIFIED', 'CSM_MPT', 'GENERIC'</param>
        public Sku(int? defaultUnitsPurchased = default(int?), bool? deleted = default(bool?), bool? discontinued = default(bool?), IList<Feature> features = default(IList<Feature>), string publishType = default(string), string skuAnalysisType = default(string), string skuDescription = default(string), string skuId = default(string), int? skuLegacyId = default(int?), string skuName = default(string), string skuType = default(string))
        {
            DefaultUnitsPurchased = defaultUnitsPurchased;
            Deleted = deleted;
            Discontinued = discontinued;
            Features = features;
            PublishType = publishType;
            SkuAnalysisType = skuAnalysisType;
            SkuDescription = skuDescription;
            SkuId = skuId;
            SkuLegacyId = skuLegacyId;
            SkuName = skuName;
            SkuType = skuType;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the number of deafult units of this SKU that can be
        /// purchased.
        /// </summary>
        [JsonProperty(PropertyName = "default_units_purchased")]
        public int? DefaultUnitsPurchased { get; set; }

        /// <summary>
        /// Gets or sets flag indicating if this SKU was soft deleted.
        /// </summary>
        [JsonProperty(PropertyName = "deleted")]
        public bool? Deleted { get; set; }

        /// <summary>
        /// Gets or sets flag indicating if this SKU is discontinued.
        /// </summary>
        [JsonProperty(PropertyName = "discontinued")]
        public bool? Discontinued { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "features")]
        public IList<Feature> Features { get; set; }

        /// <summary>
        /// Gets or sets enum indicating the publish type of this SKU. Possible
        /// values include: 'PLATFORM', 'GREENLIGHT'
        /// </summary>
        [JsonProperty(PropertyName = "publish_type")]
        public string PublishType { get; set; }

        /// <summary>
        /// Gets or sets enum indicating the SKU analysis type of this SKU.
        /// Possible values include: 'STATIC', 'DYNAMIC', 'STATIC_AND_DYNAMIC',
        /// 'NOT_APPLICABLE', 'DYNAMIC_ANALYSIS'
        /// </summary>
        [JsonProperty(PropertyName = "sku_analysis_type")]
        public string SkuAnalysisType { get; set; }

        /// <summary>
        /// Gets or sets the short description for this SKU.
        /// </summary>
        [JsonProperty(PropertyName = "sku_description")]
        public string SkuDescription { get; set; }

        /// <summary>
        /// Gets or sets the SKU ID in the Veracode Identity API.
        /// </summary>
        [JsonProperty(PropertyName = "sku_id")]
        public string SkuId { get; set; }

        /// <summary>
        /// Gets or sets the SKU ID in the Veracode database.
        /// </summary>
        [JsonProperty(PropertyName = "sku_legacy_id")]
        public int? SkuLegacyId { get; set; }

        /// <summary>
        /// Gets or sets the SKU name.
        /// </summary>
        [JsonProperty(PropertyName = "sku_name")]
        public string SkuName { get; set; }

        /// <summary>
        /// Gets or sets enum indicating the SKU type of this SKU. Possible
        /// values include: 'SDLC', 'COTS_ENTERPRISE', 'ELEARNING',
        /// 'APPLICATION', 'CSM', 'DISCOVERY', 'DYNAMICMP', 'SCA', 'DYN_APP',
        /// 'DYN_SCANS', 'DYN_SCANNER', 'SC_ACCEL_NEXTDAY', 'SC_SCA',
        /// 'SCA_AND_SC', 'SCA_UNIFIED', 'CSM_MPT', 'GENERIC'
        /// </summary>
        [JsonProperty(PropertyName = "sku_type")]
        public string SkuType { get; set; }

    }
}
