// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Veracode.ApiClients.SummaryReportApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Information about the status of discovered findings.
    /// </summary>
    public partial class FlawStatusType
    {
        /// <summary>
        /// Initializes a new instance of the FlawStatusType class.
        /// </summary>
        public FlawStatusType()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the FlawStatusType class.
        /// </summary>
        /// <param name="_new">Number of findings discovered during the first
        /// build of this application.</param>
        /// <param name="reopen">Number of findings discovered in a prior build
        /// of this application that were not new, but Veracode discovered them
        /// in the build immediately prior to this build.</param>
        /// <param name="open">Number of findings discovered in this build that
        /// Veracode also discovered in the build immediately prior to this
        /// build.</param>
        /// <param name="fixedProperty">Number of findings discovered in the
        /// prior build that Veracode did not discover in the current build.
        /// For a dyanamic analysis, Veracode verifies the findings as
        /// fixed.</param>
        /// <param name="total">Total number of findings discovered in this
        /// build.</param>
        /// <param name="notMitigated">Total number of findings discovered in
        /// this build that are not mitigated.</param>
        /// <param name="sev1Change">Number of severity-1 findings discovered
        /// in this build, minus the number of severity-1 findings discovered
        /// in the build immediately prior to this build.</param>
        /// <param name="sev2Change">Number of severity-2 findings discvoered
        /// in this build, minus the number of severity-2 findings discovered
        /// in the build immediately prior to this build.</param>
        /// <param name="sev3Change">Number of severity-3 findings discvoered
        /// in this build, minus the number of severity-3 findings discovered
        /// in the build immediately prior to this build.</param>
        /// <param name="sev4Change">Number of severity-4 findings discvoered
        /// in this build, minus the number of severity-4 findings discovered
        /// in the build immediately prior to this build.</param>
        /// <param name="sev5Change">Number of severity-5 findings discvoered
        /// in this build, minus the number of severity-5 findings discovered
        /// in the build immediately prior to this build.</param>
        /// <param name="conformsToGuidelines">Number of mitigations that
        /// adhere to your risk tolerance guidelines based on Veracode
        /// review.</param>
        /// <param name="deviatesFromGuidelines">Number of mitigations that
        /// either do not provide enough information or do not adhere to your
        /// the risk tolerance guidelines, based on Veracode review.</param>
        /// <param name="totalReviewedMitigations">Total number of mitigations
        /// that Veracode reviewed. The value may not add up to the total
        /// number of all proposed or accepted   mitigations.</param>
        public FlawStatusType(long? _new = default(long?), long? reopen = default(long?), long? open = default(long?), long? fixedProperty = default(long?), long? total = default(long?), long? notMitigated = default(long?), long? sev1Change = default(long?), long? sev2Change = default(long?), long? sev3Change = default(long?), long? sev4Change = default(long?), long? sev5Change = default(long?), long? conformsToGuidelines = default(long?), long? deviatesFromGuidelines = default(long?), long? totalReviewedMitigations = default(long?))
        {
            this._new = _new;
            Reopen = reopen;
            Open = open;
            FixedProperty = fixedProperty;
            Total = total;
            NotMitigated = notMitigated;
            Sev1Change = sev1Change;
            Sev2Change = sev2Change;
            Sev3Change = sev3Change;
            Sev4Change = sev4Change;
            Sev5Change = sev5Change;
            ConformsToGuidelines = conformsToGuidelines;
            DeviatesFromGuidelines = deviatesFromGuidelines;
            TotalReviewedMitigations = totalReviewedMitigations;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets number of findings discovered during the first build
        /// of this application.
        /// </summary>
        [JsonProperty(PropertyName = "_new")]
        public long? _new { get; set; }

        /// <summary>
        /// Gets or sets number of findings discovered in a prior build of this
        /// application that were not new, but Veracode discovered them in the
        /// build immediately prior to this build.
        /// </summary>
        [JsonProperty(PropertyName = "reopen")]
        public long? Reopen { get; set; }

        /// <summary>
        /// Gets or sets number of findings discovered in this build that
        /// Veracode also discovered in the build immediately prior to this
        /// build.
        /// </summary>
        [JsonProperty(PropertyName = "open")]
        public long? Open { get; set; }

        /// <summary>
        /// Gets or sets number of findings discovered in the prior build that
        /// Veracode did not discover in the current build. For a dyanamic
        /// analysis, Veracode verifies the findings as fixed.
        /// </summary>
        [JsonProperty(PropertyName = "fixed")]
        public long? FixedProperty { get; set; }

        /// <summary>
        /// Gets or sets total number of findings discovered in this build.
        /// </summary>
        [JsonProperty(PropertyName = "total")]
        public long? Total { get; set; }

        /// <summary>
        /// Gets or sets total number of findings discovered in this build that
        /// are not mitigated.
        /// </summary>
        [JsonProperty(PropertyName = "not_mitigated")]
        public long? NotMitigated { get; set; }

        /// <summary>
        /// Gets or sets number of severity-1 findings discovered in this
        /// build, minus the number of severity-1 findings discovered in the
        /// build immediately prior to this build.
        /// </summary>
        [JsonProperty(PropertyName = "sev1_change")]
        public long? Sev1Change { get; set; }

        /// <summary>
        /// Gets or sets number of severity-2 findings discvoered in this
        /// build, minus the number of severity-2 findings discovered in the
        /// build immediately prior to this build.
        /// </summary>
        [JsonProperty(PropertyName = "sev2_change")]
        public long? Sev2Change { get; set; }

        /// <summary>
        /// Gets or sets number of severity-3 findings discvoered in this
        /// build, minus the number of severity-3 findings discovered in the
        /// build immediately prior to this build.
        /// </summary>
        [JsonProperty(PropertyName = "sev3_change")]
        public long? Sev3Change { get; set; }

        /// <summary>
        /// Gets or sets number of severity-4 findings discvoered in this
        /// build, minus the number of severity-4 findings discovered in the
        /// build immediately prior to this build.
        /// </summary>
        [JsonProperty(PropertyName = "sev4_change")]
        public long? Sev4Change { get; set; }

        /// <summary>
        /// Gets or sets number of severity-5 findings discvoered in this
        /// build, minus the number of severity-5 findings discovered in the
        /// build immediately prior to this build.
        /// </summary>
        [JsonProperty(PropertyName = "sev5_change")]
        public long? Sev5Change { get; set; }

        /// <summary>
        /// Gets or sets number of mitigations that adhere to your risk
        /// tolerance guidelines based on Veracode review.
        /// </summary>
        [JsonProperty(PropertyName = "conforms_to_guidelines")]
        public long? ConformsToGuidelines { get; set; }

        /// <summary>
        /// Gets or sets number of mitigations that either do not provide
        /// enough information or do not adhere to your the risk tolerance
        /// guidelines, based on Veracode review.
        /// </summary>
        [JsonProperty(PropertyName = "deviates_from_guidelines")]
        public long? DeviatesFromGuidelines { get; set; }

        /// <summary>
        /// Gets or sets total number of mitigations that Veracode reviewed.
        /// The value may not add up to the total number of all proposed or
        /// accepted   mitigations.
        /// </summary>
        [JsonProperty(PropertyName = "total_reviewed_mitigations")]
        public long? TotalReviewedMitigations { get; set; }

    }
}
