// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Veracode.ApiClients.SummaryReportApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// For Manual Penetration Testing, Veracode applies the confidentiality,
    /// integrity, and availability (CIA) triad to generate the final numeric
    /// score for the application. The report lists the delivery consultants,
    /// if any, followed by scan results.
    /// </summary>
    public partial class ManualAnalysisType
    {
        /// <summary>
        /// Initializes a new instance of the ManualAnalysisType class.
        /// </summary>
        public ManualAnalysisType()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ManualAnalysisType class.
        /// </summary>
        /// <param name="ciaAdjustment">For Manual Penetration Testing, the CIA
        /// triad that Veracode applied to the security score.</param>
        /// <param name="deliveryConsultant">For Manual Penetration Testing,
        /// the names of the delivery consultants, if any.</param>
        /// <param name="rating">Letter grade for the security of this
        /// application.</param>
        /// <param name="score">Numeric score for the security of this
        /// application.</param>
        /// <param name="nextScanDue">Date when the active security policy for
        /// this application is scheduled to request the next scan.</param>
        public ManualAnalysisType(long? ciaAdjustment = default(long?), IList<string> deliveryConsultant = default(IList<string>), Module modules = default(Module), string rating = default(string), long? score = default(long?), string nextScanDue = default(string))
        {
            CiaAdjustment = ciaAdjustment;
            DeliveryConsultant = deliveryConsultant;
            Modules = modules;
            Rating = rating;
            Score = score;
            NextScanDue = nextScanDue;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets for Manual Penetration Testing, the CIA triad that
        /// Veracode applied to the security score.
        /// </summary>
        [JsonProperty(PropertyName = "cia_adjustment")]
        public long? CiaAdjustment { get; set; }

        /// <summary>
        /// Gets or sets for Manual Penetration Testing, the names of the
        /// delivery consultants, if any.
        /// </summary>
        [JsonProperty(PropertyName = "delivery_consultant")]
        public IList<string> DeliveryConsultant { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modules")]
        public Module Modules { get; set; }

        /// <summary>
        /// Gets or sets letter grade for the security of this application.
        /// </summary>
        [JsonProperty(PropertyName = "rating")]
        public string Rating { get; set; }

        /// <summary>
        /// Gets or sets numeric score for the security of this application.
        /// </summary>
        [JsonProperty(PropertyName = "score")]
        public long? Score { get; set; }

        /// <summary>
        /// Gets or sets date when the active security policy for this
        /// application is scheduled to request the next scan.
        /// </summary>
        [JsonProperty(PropertyName = "next_scan_due")]
        public string NextScanDue { get; set; }

    }
}
