// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Veracode.ApiClients.FindingsApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Category
    /// </summary>
    /// <remarks>
    /// The finding category.
    /// </remarks>
    public partial class Category
    {
        /// <summary>
        /// Initializes a new instance of the Category class.
        /// </summary>
        public Category()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Category class.
        /// </summary>
        /// <param name="description">The CWE category.</param>
        /// <param name="id">Unique ID of the category.</param>
        /// <param name="name">Category name.</param>
        /// <param name="recommendation">Category recommendation.</param>
        public Category(string description = default(string), int? id = default(int?), string name = default(string), string recommendation = default(string))
        {
            Description = description;
            Id = id;
            Name = name;
            Recommendation = recommendation;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the CWE category.
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets unique ID of the category.
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or sets category name.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets category recommendation.
        /// </summary>
        [JsonProperty(PropertyName = "recommendation")]
        public string Recommendation { get; set; }

    }
}
