// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Veracode.ApiClients.FindingsApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// EmbeddedCwe
    /// </summary>
    public partial class EmbeddedCwe
    {
        /// <summary>
        /// Initializes a new instance of the EmbeddedCwe class.
        /// </summary>
        public EmbeddedCwe()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EmbeddedCwe class.
        /// </summary>
        public EmbeddedCwe(IList<Cwe> cwes = default(IList<Cwe>))
        {
            Cwes = cwes;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cwes")]
        public IList<Cwe> Cwes { get; set; }

    }
}
