// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Veracode.ApiClients.FindingsApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// PagedResourceOfCategory
    /// </summary>
    public partial class PagedResourceOfCategory
    {
        /// <summary>
        /// Initializes a new instance of the PagedResourceOfCategory class.
        /// </summary>
        public PagedResourceOfCategory()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PagedResourceOfCategory class.
        /// </summary>
        public PagedResourceOfCategory(EmbeddedCategory _embedded = default(EmbeddedCategory), Link _link = default(Link), PageMetadata page = default(PageMetadata))
        {
            this._embedded = _embedded;
            this._link = _link;
            Page = page;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "_embedded")]
        public EmbeddedCategory _embedded { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "_link")]
        public Link _link { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "page")]
        public PageMetadata Page { get; set; }

    }
}
