on:
  push:
    branches: [main]
    paths: ["src/Veracode.ApiClients.ApplicationsApi/*"]
  pull_request:
    types: [closed]
    branches: [main]
    paths: ["src/Veracode.ApiClients.ApplicationsApi/*"]
  workflow_dispatch:

jobs:
  call-to-publish:
    uses: cuteribs/Veracode.ApiClients/.github/workflows/_publish.yml@main
    with:
      PROJECT_NAME: Veracode.ApiClients.ApplicationsApi
    secrets:
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
      