on:
  push:
    branches: [main]
    paths: ["src/Veracode.ApiClients.ApplicationsApi/*"]
  pull_request:
    types: [closed]
    branches: [main]
    paths: ["src/Veracode.ApiClients.ApplicationsApi/*"]
  workflow_dispatch:

jobs:
  call-to-publish:
    uses: ./.github/workflows/_publish.yml
    with:
      project-name: Veracode.ApiClients.ApplicationsApi
    secrets:
      nuget-token: ${{ secrets.NUGET_TOKEN }}
